---
- name: Copy RabbitMQ configuration file
  template:
    src: "{{ rabbitmq_host_config_file_path }}"
    dest: "{{ rabbitmq_config_file_path }}"
    owner: root
    group: root
    mode: 0644
  when: rabbitmq_config_check.stat.exists
  notify: Restart RabbitMQ